server:
  port: 8080

#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/hehe02?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

#ali durid
spring:
  datasource:
    url: jdbc:mysql://47.94.44.143:3306/qiandao?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunMillis: 60000
    minEvictableIdTimeMillis: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j,config
    userGlobalDataSoureStat: ture
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALz4MuKD6walFfktIkZePp0Djzw71YnxBvlAQfNmlvR1TSlP+4/z4t8LJR4FRZZS2DzmurigVENufQ92W0L5S/MCAwEAAQ==


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.qiandao.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

---

# redis
spring:
  redis:
    host : 47.94.44.143
    port : 6379
    password: 123456
    timeout:
    jedis :
      pool :
        maxTotal: 100
        maxWaitMillis : 100000
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

---

# RabbitMq
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true   #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true
    template:
      mandatory: true
  devtools:
    restart:
      enabled: false

---

fdfs:
  so-timeout: 3000
  connectTimeout: 2000
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 192.168.25.133:22122
